plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

//Dependencies for testing and javalin
dependencies {
    implementation 'io.javalin:javalin:7.2.3'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
}

//Added a way to see testing outputs
test {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
    }
}

application {
    mainClass = 'WebApp'
}

tasks.named('run') {
    standardInput = System.in
}