services:

  app:
      build: .
      ports:
        - "7070:7070"
      environment:
        DB_URL: jdbc:postgresql://database:5432/xsandos
        DB_USER: postgres
        DB_PASSWORD: password
      depends_on:
        - database

  database:
    build: ./database
    environment:
      POSTGRES_DB: xsandos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"